### ISSUE TITLE
error: ‘router’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by fabiorico** [monkey/duda-examples#4]
Hello

When I run the command "dudac -w duda-examples/001_hello_world" i get the following error on build:

main.c: In function ‘_duda_main’:
main.c:95:5: error: ‘router’ undeclared (first use in this function)
     router->map("/foo/", cb_foo);
     ^
main.c:95:5: note: each undeclared identifier is reported only once for each function it appears in
make: **\* [main.o] Error 1

I am using examples from DST1 branch.

**Comment by edsiper** [comment]
You are using examples from DST2, if you look at the DST-1 hello world you will see there is no reference to the 'router' object:

https://github.com/monkey/duda-examples/blob/dst-1/001_hello_world/main.c#L77

**Comment by fabiorico** [comment]
Solved.
You are right. I was systematically cloning the master branch.  My bad.
